service: resiz-io

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  stage: ${opt:stage, "master"}
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

functions:
  app:
    package:
      patterns:
        - "!node_modules/**"
    handler: app.main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  customDomain:
    domainName: dev.resiz.io
    certificateName: '*.resiz.io'
    createRoute53Record: true
    endpointType: 'edge'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
    certificateArn: arn:aws:acm:us-east-1:494890851710:certificate/aecfe7e9-6847-49f1-bb85-a1d91f25cec3
